apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mini-dynamo

resources:
  - namespace.yaml
  - config.yaml
  - redis.yaml
  - prefill.yaml
  - decode.yaml
  - router.yaml
  - observability/jaeger.yaml
  - observability/prometheus.yaml
  - observability/grafana.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=observability/files/prometheus.yml
  - name: grafana-datasources
    files:
      - datasources.yml=observability/files/grafana-datasources.yml
  - name: grafana-dashboards-provider
    files:
      - dashboards.yml=observability/files/grafana-dashboards-provider.yml
  - name: grafana-dashboards
    files:
      - mini-dynamo.json=observability/files/mini-dynamo.json
